# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FastConsumption' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FastConsumption
  pod 'Bond', '~> 6.5.2'
  pod 'CocoaLumberjack', '~> 3.3.0'
  pod 'CocoaLumberjack/Swift'
  pod 'DeviceKit', '~> 1.4.0'
  pod 'Eureka', '~> 4.0.1'
  pod 'FLEX', '~> 2.4.0', :configurations => ['Debug']
  pod 'IGListKit', '~> 3.1.1'
  pod 'IQKeyboardManagerSwift', '~> 5.0.6'
  pod 'Kingfisher', '~> 4.3.1'
  pod 'KeychainAccess', '~> 3.1.0'
  pod 'Moya', '~> 10.0.1'
  pod 'Moya/RxSwift'
  pod 'Permission', '~> 2.0.4'
  pod 'PromiseKit', '~> 4.5.0'
  pod 'PromiseKit/CoreLocation'
  pod 'PromiseKit/Alamofire'
  pod 'Realm', '~> 3.0.2'
  pod 'ReSwift', '~> 4.0.0'
  pod 'Reusable', '~> 4.0.0'
  pod 'RxCocoa', '~> 4.0.0'
  pod 'RxSwift', '~> 4.0.0'
  pod 'R.swift', '~> 4.0.0'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'SnapKit', '~> 4.0.0'
  pod 'SwiftDate', '~> 4.4.2'
  pod 'SwiftyJSON', '~> 4.0.0'
  pod 'YogaKit', '~> 1.6.0'
  pod 'YYCache', '~> 1.0.4'
  pod 'YYText', '~> 1.0.7'


  target 'FastConsumptionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FastConsumptionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
