//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 1 images.
  struct image {
    /// Image `side_bar_bg`.
    static let side_bar_bg = Rswift.ImageResource(bundle: R.hostingBundle, name: "side_bar_bg")
    
    /// `UIImage(named: "side_bar_bg", bundle: ..., traitCollection: ...)`
    static func side_bar_bg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.side_bar_bg, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `LoginingStoryboard`.
    static let loginingStoryboard = _R.storyboard.loginingStoryboard()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "LoginingStoryboard", bundle: ...)`
    static func loginingStoryboard(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.loginingStoryboard)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try loginingStoryboard.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct loginingStoryboard: Rswift.StoryboardResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let loginViewControllerID = StoryboardViewControllerResource<LoginViewController>(identifier: "LoginViewControllerID")
      let name = "LoginingStoryboard"
      let registerViewControllerID = StoryboardViewControllerResource<RegisterViewController>(identifier: "RegisterViewControllerID")
      let resetPasswordViewControllerID = StoryboardViewControllerResource<ResetPasswordViewController>(identifier: "ResetPasswordViewControllerID")
      let retrievePasswordViewController = StoryboardViewControllerResource<RetrievePasswordViewController>(identifier: "RetrievePasswordViewController")
      
      func loginViewControllerID(_: Void = ()) -> LoginViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: loginViewControllerID)
      }
      
      func registerViewControllerID(_: Void = ()) -> RegisterViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: registerViewControllerID)
      }
      
      func resetPasswordViewControllerID(_: Void = ()) -> ResetPasswordViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: resetPasswordViewControllerID)
      }
      
      func retrievePasswordViewController(_: Void = ()) -> RetrievePasswordViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: retrievePasswordViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.loginingStoryboard().registerViewControllerID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'registerViewControllerID' could not be loaded from storyboard 'LoginingStoryboard' as 'RegisterViewController'.") }
        if _R.storyboard.loginingStoryboard().resetPasswordViewControllerID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'resetPasswordViewControllerID' could not be loaded from storyboard 'LoginingStoryboard' as 'ResetPasswordViewController'.") }
        if _R.storyboard.loginingStoryboard().loginViewControllerID() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'loginViewControllerID' could not be loaded from storyboard 'LoginingStoryboard' as 'LoginViewController'.") }
        if _R.storyboard.loginingStoryboard().retrievePasswordViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'retrievePasswordViewController' could not be loaded from storyboard 'LoginingStoryboard' as 'RetrievePasswordViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
